let mycar = "Renault Wind (N)"
let price = "8000EUR";
let year = "2010 - ...";
let color = "white";
let speed = "190km/h";

console.log(mycar, price, year, color, speed)

const car = { mycar: "Renault Wind (N)", price: "8000EUR", year: "2010 - ...", color: "white", speed: "190km/h", };

console.log(car)

const car1 = ['Renault Wind (N)', '8000EUR', '2010 - ...', 'white', '190km/h'];

console.log(car1[0]);

mycar = "Porsche 911"
price = "90000USD";
year = "2020";
color = "red";
speed = "293km/h";

console.log(mycar, price, year, color, speed);

const NewCar = { mycar: "Porsche 911", price: "90000USD", year: "2020", color: "red", speed: '293km/h' };

console.log(NewCar);

const NewCar1 = ["Porsche 911", "90000USD", "2020", "red", "293km/h"];

console.log(NewCar1[1]);