let car = { name: "porsh",
 size: "large", 
 src: "https://www.cartube.co.il/images/stories/porche/p-911/2020/Porsche-911_Targa_4-2021-1600-02-970px.jpg",
color: "black",
 weight: "2l"};
 
 console.log(car.name);
 console.log(car);
 
 document.getElementById("porshPIC");


 const arr = [ 'kuka', 'chucha', 'pupa', 'kuku', "tutu"]
 console.log(arr);
 console.log(arr[0]);
 console.log(arr[1]);
 console.log(arr[2]);
 console.log(arr[3]);
 console.log(arr[4]);

 arr[0]= 22
 

// car//
let name = 'porsh';
let type = '911';
let color = 'black';
let speed = '289';
let price = '1300000';
let year = '2020';

const cars = { name :'porsh', type : '911', color: 'black', speed: '289', price: '1300000', year: '2020'};
 console.log(cars);
 console.log(cars.name);
 console.log(cars.type);
 console.log(cars.color);
 console.log(cars.speed);
 console.log(cars.price);
 console.log(cars.year);






