
 

// car//
let name = 'porsh';
let type = '911';
let color = 'black';
let speed = '289';
let price = '1300000';
let year = '2020';

const cars = { name :'porsh', type : '911', color: 'black', speed: '289', price: '1300000', year: '2020'};
 console.log(cars);
 console.log(cars.name);
 console.log(cars.type);
 console.log(cars.color);
 console.log(cars.speed);
 console.log(cars.price);
 console.log(cars.year);

const cars = [newCAR]
const newCAR = {  name :'porsh', type : '911', color: 'black', speed: '289', price: '1300000', year: '2020'};






