let uniqcategory = [];

const products = [
  {
    category: 'cars',
    price: 120000,
    inStoreSince: '2020-01-23',
    brand: 'Hyundai',
    model: 'i10',
    recommendations: 20,
    image:
      'https://www.subaru-global.com/ebrochure/XV/2019my/EN/exterior/assets/FHI/MY19/XV/EN/Exterior/mp4-svg-360/exterior_360/d_exterior_360_01_01.jpg?43d1fdab5753f55134ca114abf2cd33a',
    description: 'achala auto',
    name: 'i10',
    store: 'moshe and co.',
    isdn: 'drytertyertyerh',
  },
  {
    category: 'mobile',
    price: 5500,
    inStoreSince: '2020-09-22',
    brand: 'Iphone',
    model: 'iPhone 12 Pro',
    recommendations: 85,
    image:
      'https://www.gizmochina.com/wp-content/uploads/2020/05/iphone-12-pro-max-family-hero-all-600x600.jpg',
    description: 'very high end mobile phone',
    name: 'iPhone 12 Pro',
    store: 'Apple',
    isdn: 'SNJ28DN1900SMC89S82',
  },
  {
    category: 'fashion',
    price: 2000,
    inStoreSince: '2020-04-05',
    brand: 'GUCCI',
    model: 'Ace Sneakers',
    recommendations: 85,
    image:
      'https://cache.net-a-porter.com/images/products/1009127/1009127_in_920_q80.jpg',
    description: 'nice shoes',
    name: 'GUCCI Ace Sneakers',
    store: 'net a porter',
    isdn: 'ASMJDKK29CM10DCM22',
  },
  {
    category: 'electricity',
    price: 'Number',
    inStoreSince: '2019-02-22',
    brand: 'Electra',
    model: 'ELECTRA 5100',
    recommendations: 92,
    image:
      'https://www.payngo.co.il/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/5/6/5600-1_1.jpg',
    description: 'good washer',
    name: 'Electra ELECTRA 5100',
    store: 'electra',
    isdn: 'SDMKMKS929321CSSDQSDZXX',
  },
  {
    category: 'fashion',
    price: 50,
    inStoreSince: '2020-07-10',
    brand: 'nike',
    model: 'total90',
    recommendations: 40,
    image:
      'https://www.shopcleats.me/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/n/i/nike-total-90-laser-se-fg-remake-boots-white-yello-black-6.jpg',
    description: 'beautiful shoe that does the job!',
    name: 'total90',
    store: 'sports naharya',
    isdn: 'afyuagsuy',
  },
  {
    category: 'cars',
    price: 140000,
    inStoreSince: '2020-01-09',
    brand: 'hyundai',
    model: 'veloster',
    recommendations: 80,
    image:
      'https://editorial.pxcrush.net/carsales/general/editorial/2020-veloster-turbo-premium-11.jpg?width=1024&height=683&aspect=pad',
    description: 'georgeus car, dying to have it',
    name: 'veloster',
    store: 'almog motors',
    isdn: 'uhfjalsbdjqwhd',
  },
  {
    category: 'mobile',
    price: 1200,
    inStoreSince: '2020-02-05',
    brand: 'google',
    model: 'pixel 5',
    recommendations: 30,
    image:
      'https://i.gadgets360cdn.com/products/large/Pixel-5-DB-369x800-1601538019.jpg?downsize=*:420&output-quality=80',
    description: 'solid and reliable mobile phone',
    name: 'pixel 5',
    store: 'omer phone',
    isdn: 'asdwdqwddqwdqw',
  },
  {
    category: 'fashion',
    price: 120,
    inStoreSince: '2020-03-23',
    brand: 'vans',
    model: 'm',
    recommendations: 90,
    image: 'String',
    description: 'https://img.zap.co.il/pics/0/0/8/1/56721800b.gif',
    name: 'blue Tshirt',
    store: 'BikeCafe',
    isdn: 'cbkcbkw',
  },
  {
    category: 'fashion',
    price: 1189,
    inStoreSince: '2020-07-27',
    brand: 'bose',
    model: 'Frames Alto',
    recommendations: 10,
    image: 'https://img.zap.co.il/pics/3/3/2/5/52765233b.gif',
    description: 'Unisex sunglasses',
    name: 'sunglasses',
    store: 'נbug',
    isdn: 'bdfbbd',
  },
  {
    category: 'electricity',
    price: 1750,
    inStoreSince: '2020-01-23',
    brand: 'lg',
    model: 'tv 55 inch',
    recommendations: 10,
    image: '',
    description: 'tv for home',
    name: 'lg tv 55 inch',
    store: 'alam',
    isdn: 'dfdfxf',
  },

  {
    category: 'Computers',
    price: 3500,
    inStoreSince: '2020-01-23',
    brand: 'hp',
    model: 'leptop 14 inch',
    recommendations: 50,
    image:
      'https://img.zap.co.il/dealsImages/943/7/943-637403856539846510_1341289c.jpg',
    description: 'computer for home and work',
    name: 'hp laptop 14 inch',
    store: 'bag',
    isdn: 'jpijhkjg',
  },

  {
    category: 'mobile',
    price: 3500,
    inStoreSince: '2020-01-23',
    brand: 'apple',
    model: 'iphone 11',
    recommendations: 35,
    image: '',
    description: 'good phone',
    name: 'iphone 11',
    store: 'apple store',
    isdn: 'johoij',
  },
  {
    category: 'computers',
    price: 968,
    inStoreSince: '2020-01-23',
    brand: 'Asus',
    model: '  L203NA-FD126TS',
    recommendations: 138,
    image: 'https://www.bestmobile.co.il/media/catalog/product/2/0/2031.png',
    description: 'achala computer',
    name: '11.6" L203NA-FD126TS 4G',
    store: 'BestMobil',
    isdn: 'drytertyertyerh',
  },

  {
    category: 'computers',
    price: 2789,
    inStoreSince: '2020-04-15',
    brand: 'Lenovo',
    model: ' Lenovo V14 IIL 82C400SDIV',
    recommendations: 38,
    image: 'https://img.zap.co.il/pics/5/1/9/1/58201915c.gif',
    description: 'achala computer',
    name: '11.6" L203NA-FD126TS 4G',
    store: 'Pc-Online',
    isdn: 'drytertyertyerh',
  },
  {
    category: 'cars',
    price: 118000,
    inStoreSince: '2018-01-1',
    brand: 'tesla',
    model: '3',
    recommendations: 100,
    image: '',
    description: 'the best sadan in the market',
    name: 'tesla model 3 - electric ',
    store: 'tesla.com',
    isdn: '15hhbvy1',
  },
  {
    category: 'cars',
    price: 250000,
    inStoreSince: '2015-01-1',
    brand: 'tesla',
    model: 'S',
    recommendations: 100,
    image: '',
    description: 'the best primium sadan in the market',
    name: 'tesla model S - electric ',
    store: 'tesla.com',
    isdn: '15hhbvy1',
  },
  {
    category: 'computers',
    price: 2300,
    inStoreSince: '2020-01-1',
    brand: 'lenovo',
    model: 'flex 5',
    recommendations: 70,
    image: '',
    description: 'tuch screen and pen include 2in1',
    name: 'flex 5',
    store: 'best buy',
    isdn: 'drytertyerh',
  },
  {
    category: 'mobile',
    price: 1170,
    inStoreSince: '2020-02-01',
    brand: 'xioumi',
    model: 'k30 ultra',
    recommendations: 80,
    image: '',
    description: 'best phone',
    name: 'k30 ultra',
    store: 'hemilton',
    isdn: 'dr173rtyerh',
  },
  {
    category: 'FASHION',
    price: 100,
    inStoreSince: '20-11-20',
    brand: 'bilabol',
    model: 'shirt',
    recommendations: 200,
    image:
      'https://ae01.alicdn.com/kf/U997bf8243284402ea3107859f9dfb240z/T-shirt-BILLABONG-Gold-Coast-Tee.jpg',
    description: 'best t-shirt',
    name: 'holza',
    store: 'bilaspong',
    isdn: 'ah sheli bahsheli',
  },
  {
    category: 'Fashion',
    price: 32,
    inStoreSince: '7-2-92',
    brand: 'galcha',
    model: 'pants',
    recommendations: 0912,
    image:
      'https://cdn1.jolicloset.com/imgr/full/2019/08/140404-1/orange-silk-gucci-pants.jpg',
    description: 'gucci gang',
    name: 'pants',
    store: 'bug',
    isdn: 'ah sheli bahsheli',
  },
  {
    category: 'Fashion',
    price: 69420,
    inStoreSince: '7-2-52',
    brand: 'shalom',
    model: 'socks',
    recommendations: 99,
    image:
      'https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1539362705/557012_3K227_9764_001_100_0000_Light-Baby-GG-socks.jpg',
    description: 'lol',
    name: 'socks',
    store: 'supersal',
    isdn: 'ah sheli bahsheli',
  },
  {
    category: 'mobile',
    price: 526,
    inStoreSince: '2020-01-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'Wireless earphones from Apple',
    name: 'String',
    store: 'SCOPE Digital',
    isdn: 'zxmvbc869xcv',
  },
  {
    category: 'mobile',
    price: 540,
    inStoreSince: '2020-05-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'Wireless earphones from Apple',
    name: 'String',
    store: 'MobileLand',
    isdn: 'dh34ycxbxb',
  },
  {
    category: 'Vacuum cleaners',
    price: '1200',
    inStoreSince: '2020-11-15',
    brand: 'Daison',
    model: 'V12',
    recommendations: 1250,
    image: 'https://img.zap.co.il/pics/0/1/7/8/47368710b.gif',
    description: '8 cores, 12 threads',
    name: 'V12 Daison Vacuum cleaner',
    store: 'Daison',
    isdn: '123hsnbjh123',
  },
  {
    category: 'mobile',
    price: 575,
    inStoreSince: '2020-01-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zx1mvbc869xcv',
  },

  {
    category: 'electricity',
    price: 375,
    inStoreSince: '2020-01-03',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '24',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zxmvbc8639xcv',
  },
  {
    category: 'electricity',
    price: 428,
    inStoreSince: '2019-01-01',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '38',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zxmvbc8629xcv',
  },
  {
    category: 'electricity',
    price: 429,
    inStoreSince: '2020-04-01',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '14',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'WMicro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'z5xmvbc869xcv',
  },
  {
    category: 'earphones',
    price: 526,
    inStoreSince: '2020-01-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'Wireless earphones from Apple',
    name: 'String',
    store: 'SCOPE Digital',
    isdn: 'zxmvbc869xcv',
  },
  {
    category: 'earphones',
    price: 540,
    inStoreSince: '2020-05-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'Wireless earphones from Apple',
    name: 'String',
    store: 'MobileLand',
    isdn: 'dh34ycxbxb',
  },
  {
    category: 'earphones',
    price: 575,
    inStoreSince: '2020-01-01',
    brand: 'Apple',
    model: 'AirPods 2',
    recommendations: '34',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zx1mvbc869xcv',
  },
  {
    category: 'Electric explains',
    price: 375,
    inStoreSince: '2020-01-03',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '24',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zxmvbc8639xcv',
  },
  {
    category: 'Electric explains',
    price: 428,
    inStoreSince: '2019-01-01',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '38',
    image: 'https://img.zap.co.il/pics/0/2/2/6/43436220c.gif',
    description: 'Micro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'zxmvbc8629xcv',
  },
  {
    category: 'Electric explains',
    price: 429,
    inStoreSince: '2020-04-01',
    brand: 'Samsung',
    model: 'MS23K3513AS',
    recommendations: '14',
    image: 'https://img.zap.co.il/pics/9/4/2/1/49811249b.gif',
    description: 'WMicro 23 Litters',
    name: 'String',
    store: 'Game Storm',
    isdn: 'z5xmvbc869xcv',
  },
  {
    category: 'Computers',
    price: '1000',
    inStoreSince: '2020-04-15',
    brand: 'intel',
    model: 'i5-10500',
    recommendations: 4560,
    image:
      'https://www.google.com/search?q=intel+i510500&sxsrf=ALeKk01KkzNz98WQzXxXq_-yO4lE_navbg:1605806351722&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjulLDpjo_tAhVmWxUIHdyrB8cQ_AUoAXoECAcQAw&biw=2133&bih=1041#imgrc=JrlB0DCZvXzrjM',
    description: '6 cores, 12 threads',
    name: 'i5-10500k',
    store: 'intel store',
    isdn: '123hnbjh123',
  },
  {
    category: 'computers',
    price: '9200',
    inStoreSince: '2018-11-15',
    brand: 'intel',
    model: 'i5-9600k',
    recommendations: 12780,
    image:
      'https://www.ebay.com/i/333303102982?mkevt=1&siteid=1&mkcid=2&mkrid=711-153320-877651-5&source_name=google&mktype=pla_ssc&campaignid=11227688602&groupid=109637828346&targeted=pla-293946777986&MT_ID=&adpos=&device=c&googleloc=20514&itemid=333303102982&merchantid=116792603&geo_id=100&gclid=CjwKCAiAzNj9BRBDEiwAPsL0d4An78lLBihzNR7N5F-lWGUg4555cYx463oazuAupZLp9teM46ptLBoC_GwQAvD_BwE',
    description: '6 cores, 6 threads',
    name: 'i5-9600k',
    store: 'intel store',
    isdn: '123hnbjh123',
  },
];

function RenderProductScreen(product) {
  const BodyContainer = document.getElementById('BodyContainer');

  const card = `<div class="card text-center">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link active" href="#">Active</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>`;

  BodyContainer.innerHTML = card;
}
